### ISSUE TITLE
possibility to change data?

### ISSUE THREAD

**Issue by vsboost** [joeyoravec/j2534-logger#1]
love this logger, thanks for taking the time to create it, was wondering if its possible to modify a data frame in one direction?

**Comment by joeyoravec** [comment]
This code does not include a feature like that, but inside ptshim32/shim_frontend.cpp you could hardcode something to modify the parameters before the actual `_PassThruWriteMsgs` gets called:
```
	if (pNumMsgs != NULL)
		reqNumMsgs = *pNumMsgs;
	dbug_printmsg(pMsg, _T("Msg"), pNumMsgs, true);
        // TODO: Modify pMsg right here, before attempting to transmit
	retval = _PassThruWriteMsgs(ChannelID, pMsg, pNumMsgs, Timeout);
	if (pNumMsgs != NULL)
		dtDebug(_T("  sent %ld of %ld messages\n"), *pNumMsgs, reqNumMsgs);
```
or vice-versa for the Read.
